プロフィールページを更新
jaoafa/jaoweb4 pull request #126
Opened 2023-06-17 04:23 UTC by Omuretsu

表題のとおりです。

2023-06-17 04:24 UTC, Omuretsu commented on src/content/4.support/3.profiles.md
> +created: 2021-04-14
createdのデータ、必要ですか？

2023-06-18 08:28 UTC, Hiratake requested changes
本文については、そのまま持ってきてるだけだと思うので、そっとしときましょう…
一応こちらでもなんとなく考えてるものはあるのですが、なんか「こういうふうにしたらいいのでは？」みたいなのがあれば書いといてもらえると…アイデアはあればあるだけ良いので。

2023-06-18 08:28 UTC, Hiratake commented on src/content/4.support/3.profiles.md
> +created: 2021-04-14
運営者情報のページは、おそらく
- 記事作成日不要
- 記事更新日は必要
だと思うので、 https://github.com/jaoafa/jaoweb4/pull/74#issuecomment-1491898961 にあるように `created: null` を指定すると良いです。
```suggestion
created: null
```

2023-06-18 08:28 UTC, Hiratake commented on src/content/4.support/3.profiles.md
> +image: https://storage.jaoafa.com/f54f2539629b70b8f3d78cc694236081.png
このへんどうするかちゃんと決めていないので、いったん削除しておいてほしいです。

`description` に関しては、Google検索をしたときに出てくるページの説明文などに使われるものですが、いまのところ本文の最初の方が自動的に使われるようになっています。
ただ、ページの説明文を別のところで使うかもみたいな話（ #137 とか）が出ているので、変更になるかもしれません。

`image` については、これまでは指定した画像がページのタイトル下に表示されたり、SNSでシェアしたときに表示される画像として使われたりしていました。
が、現状大半がデフォルト画像のままとなっており、それだったらわざわざ画像をタイトル下に表示するとかしなくても良いだろうと判断いたしました。
ただ、SNSでシェアしたときの画像については、「ちゃんとした画像を設定して目立つようにしたい！」「適切な画像を設定してアクセス数が増えるようにしたい」などといったケースも考えられます。そういった場合にどうするかは今後検討します。（一応 `head.image` or `image` に指定した画像がSNSでシェアしたときに表示される画像として使われるはずですが、変更するかもしれないので）
```suggestion
```

2023-06-18 08:28 UTC, Hiratake commented on src/content/4.support/3.profiles.md
> -layout: article
これは記事ページ用のレイアウトを適用するための記述なので、残しておいてほしいです。
他のページも、入れてあると思います。

基本的には、ほとんどのページが記事ページなので、これを書かなくても良いようにしたいのですが、使っているライブラリの不具合なのか仕様なのか、なんかうまくいかないので…（最新版に上げたら直るのかもですが、更新しようとすると動かなくなるので検証ができてないです）

2023-06-18 08:38 UTC, Omuretsu commented on src/content/4.support/3.profiles.md
> -layout: article
https://github.com/jaoafa/jaoweb4/pull/126/commits/8f3fd08a569bb467f3902bf3a15fb9c397dba331 で対応しました。

2023-06-18 08:49 UTC, Omuretsu commented on src/content/4.support/3.profiles.md
> +image: https://storage.jaoafa.com/f54f2539629b70b8f3d78cc694236081.png
了解しました。

2023-06-18 09:43 UTC, Omuretsu commented on src/content/4.support/3.profiles.md
> +created: 2021-04-14
https://github.com/jaoafa/jaoweb4/pull/126/commits/bb2c511b2b9bd916d14860815466f50704b9ec73 で対応しました。

2023-06-18 10:24 UTC, book000 approved these changes

2023-06-18 10:30 UTC, Hiratake commented on src/content/4.support/3.profiles.md
> +created: 2021-04-14
🙏

2023-06-18 10:30 UTC, Hiratake commented on src/content/4.support/3.profiles.md
> -layout: article
👌

2023-06-18 10:30 UTC, Hiratake approved these changes

2023-06-18 10:31 UTC, merged