運営者情報ページの各ユーザ情報の表示を変更
jaoafa/jaoweb4 pull request #145
Opened 2023-06-19 12:58 UTC by Hiratake

各ユーザの情報をテーブル形式で出していたのを、調整しました。
名前やら説明文やらは、いったん仮で入れています。（わからんので）

2023-06-19 12:58 UTC, Hiratake commented
ユーザ情報を別のとこに保存して参照できるようにしたさはある。
ブログ記事とかの front-matter に入れる執筆者情報に、毎回名前やらアイコン画像やら指定するのめんどいし、それとあわせてなんかいい感じに…

2023-06-19 15:56 UTC, book000 requested changes

2023-06-19 15:56 UTC, book000 commented on src/components/content/ContentUser.vue
> +          </div>
ほぼ好みみたいなものなのですが、ユーザーページは「その人物に紐づくもの」というより、「Minecraftアカウントに紐づくもの」という認識です。リンクさせるのはハンドルネームよりかはMinecraft IDかなあと思います。

あとハンネのところに下線が入ってるの、微妙にかっこわるい…

![image](https://github.com/jaoafa/jaoweb4/assets/8929706/68cfe906-427e-4a96-b28f-d5cb35d3bd65)

2023-06-19 15:56 UTC, book000 commented on src/components/content/ContentUser.vue
> +          </div>
意図的なものであるならごめんなさいなのですが、ハンドルネームとMinecraft IDの位置合わせが上側になっているのが気になります。ベースラインで合わせたほうが良いかなあと感じます

![image](https://github.com/jaoafa/jaoweb4/assets/8929706/53d075cb-f44c-4fdd-ac9e-af7967896a36)

2023-06-19 23:13 UTC, Hiratake commented on src/components/content/ContentUser.vue
> +          </div>
めっちゃ好みの問題かもしれんけど、内容ごとにコメント分けてほしいかも…
内容ごとにresolveできないので（消して書き直すまではしなくていいですが）

指摘点については夜とか明日とかに見るなどします

2023-06-20 01:41 UTC, book000 commented on src/components/content/ContentUser.vue
> +          </div>
分けたつもりだったのですが、対象範囲が同じなんで一緒にされましたね…どうしたらいいんですかねこういう場合

2023-06-20 01:57 UTC, book000 commented on src/components/content/ContentUser.vue
> +          </div>
後者を `Minecraft: XXXXX` のところにして無理やり別範囲にするしかないのかなあ。

2023-06-20 15:18 UTC, Hiratake commented on src/components/content/ContentUser.vue
> +          </div>
> ほぼ好みみたいなものなのですが、ユーザーページは「その人物に紐づくもの」というより、「Minecraftアカウントに紐づくもの」という認識です。リンクさせるのはハンドルネームよりかはMinecraft IDかなあと思います。

たしかにそうですね。usersのページもminecraftアカウントごとになっているので、名前よりminecraft idのほうにリンクをつけるのが良いですね。変更します。

2023-06-20 15:26 UTC, Hiratake commented on src/components/content/ContentUser.vue
> +          </div>
> ハンドルネームとMinecraft IDの位置合わせが上側になっているのが気になります。

中央に揃えるの、むずかしいですよね。調整してみます…

2023-06-20 15:28 UTC, Hiratake commented on src/components/content/ContentUser.vue
> +          </div>
> 分けたつもりだったのですが、対象範囲が同じなんで一緒にされましたね…

同じ行を指定したけど、普通に別のスレッドになってる気がする…
https://github.com/jaoafa/jaoweb4/pull/149#pullrequestreview-1488386710

範囲指定だと一緒にされる…？

2023-06-20 21:56 UTC, book000 commented on src/components/content/ContentUser.vue
> +          </div>
> 中央に揃えるの、むずかしいですよね。調整してみます…

むしろ上下中央より下に合わせたほうがきれいかなあって思ったりしています。どうでしょう？

2023-06-22 11:43 UTC, Hiratake commented on src/components/content/ContentUser.vue
> +          </div>
なんとなく調整してみました

2023-06-22 11:45 UTC, Hiratake commented
mainマージしたらtextlintでエラーになっちゃった

2023-06-22 12:10 UTC, book000 commented
`Web サイト` がいいか、`ウェブサイト` でいいかは議論の余地がありそう（個人的には `Web サイト` 派です）なので、必要があればtextlintのルールをなんとかします

2023-06-22 12:13 UTC, Hiratake commented
サイト内で `Web サイト` で統一しますか

2023-06-22 12:15 UTC, book000 commented
じゃあ別PRで対応します。今このタイミングだとちょっとつらいので今日夜中or明日にでも

2023-06-23 13:23 UTC, book000 commented on src/components/content/ContentUser.vue
> +          </div>
![image](https://github.com/jaoafa/jaoweb4/assets/8929706/c6314dbf-d2cf-4c16-940a-ddad14ff7ef5)

いいですね、文句ないです。Resolveします

2023-06-23 13:37 UTC, book000 requested changes

2023-06-23 13:37 UTC, book000 commented on src/content/4.support/3.profiles.md
> +- 主にウェブサイト・システムのデザインや実装などを担当
```suggestion
- 主に Web サイト・システムのデザインや実装などを担当
```

#152 での変更に伴い、この箇所の変更が必要です

2023-06-23 13:40 UTC, Omuretsu reviewed
気になったことが何点か…
閲覧環境:iPhone13mini iOS16.5 Safari

(1)MCIDの表示位置
IDの長短に関係なく、ハンドルネームとMCIDの間は改行した方がいいと思います。
(統一感が欲しいよね)
![IMG_0606](https://github.com/jaoafa/jaoweb4/assets/75904606/2cb155ed-10e4-4d3d-85c8-ec538c76157c)

(2)各項目の揃えについて
これって現段階で左揃えになってますか？
揃えた方が綺麗に見える気がしますが、実はもうなってて錯覚でズレてるように見えるだけ？
![IMG_0607](https://github.com/jaoafa/jaoweb4/assets/75904606/35a1c42a-3526-4a59-bfb6-3c8865f52a72)

2023-06-23 13:48 UTC, Omuretsu requested changes

2023-06-23 13:48 UTC, Omuretsu commented on src/content/4.support/3.profiles.md
> +- 役割
```suggestion
- サスケ・ディナー
```

2023-06-23 13:50 UTC, Omuretsu commented on src/components/content/ContentUser.vue
気になったことが何点か…
閲覧環境:iPhone13mini iOS16.5 Safari

(1)MCIDの表示位置
IDの長短に関係なく、ハンドルネームとMCIDの間は改行した方がいいと思います。
(統一感が欲しいよね)
![IMG_0606](https://github.com/jaoafa/jaoweb4/assets/75904606/2cb155ed-10e4-4d3d-85c8-ec538c76157c)

(2)各項目の揃えについて
これって現段階で左揃えになってますか？
揃えた方が綺麗に見える気がしますが、実はもうなってて錯覚でズレてるように見えるだけ？
![IMG_0607](https://github.com/jaoafa/jaoweb4/assets/75904606/35a1c42a-3526-4a59-bfb6-3c8865f52a72)

2023-06-23 13:51 UTC, Omuretsu requested changes

2023-06-23 13:51 UTC, Omuretsu commented on src/content/4.support/3.profiles.md
> +- 役割
```suggestion
- 鯖落とし
```

2023-06-23 14:08 UTC, book000 requested changes

2023-06-23 14:08 UTC, book000 commented on src/content/4.support/3.profiles.md
> +- 役割
```suggestion
- Web サイト、Minecraft サーバ、Discord サーバなどの全般管理・運用
- プラグインや Bot の開発・管理・運用
```

2023-06-23 14:12 UTC, Omuretsu commented on src/content/4.support/3.profiles.md
> +- 役割
ごめんなさい、入れるところを間違えました。

2023-06-23 14:29 UTC, book000 requested changes

2023-06-23 14:29 UTC, book000 commented on src/content/4.support/3.profiles.md
> +- 役割
```suggestion
- お問い合わせ対応、コミュニティ保全管理
```

2023-06-23 14:29 UTC, book000 commented on src/content/4.support/3.profiles.md
> +- 役割
```suggestion
- 鯖落とし
- プラグインや Bot の開発補助
```

2023-06-23 14:29 UTC, book000 commented on src/content/4.support/3.profiles.md
> +- 役割
```suggestion
- 中央市の管理、荒らし対応
- Web サイト編集
```

2023-06-23 14:29 UTC, book000 commented on src/content/4.support/3.profiles.md
> +- 役割
```suggestion
- サスケ・ディナー
- 運営業務の補助
```

2023-06-23 14:29 UTC, book000 commented on src/content/4.support/3.profiles.md
> +- 役割
```suggestion
- プラグインや Bot の開発補助・保守
```

2023-06-23 14:29 UTC, book000 commented on src/content/4.support/3.profiles.md
> +- 役割
```suggestion
- 運営業務の補助
```

2023-06-24 00:13 UTC, Hiratake commented on src/content/4.support/3.profiles.md
> +- 主にウェブサイト・システムのデザインや実装などを担当
変更しました。

2023-06-24 00:19 UTC, Hiratake commented on src/components/content/ContentUser.vue
> (1)MCIDの表示位置
> IDの長短に関係なく、ハンドルネームとMCIDの間は改行した方がいいと思います。
> (統一感が欲しいよね)

画面幅内に収まらなくなったら改行する、という表示に統一しています。
名前やIDの長さは可変長であり、どのような長さになるか予測ができません。

> (2)各項目の揃えについて
> これって現段階で左揃えになってますか？
> 揃えた方が綺麗に見える気がしますが、実はもうなってて錯覚でズレてるように見えるだけ？

左揃えになっています。フォントや文字の大きさが違うので、どうしてもそのように見えてしまいます。

![image](https://github.com/jaoafa/jaoweb4/assets/23224932/12469556-7997-4489-871a-cf805cfabbeb)

2023-06-24 00:24 UTC, Hiratake commented on src/content/4.support/3.profiles.md
> +- 役割
各ユーザの説明のところは、そのひとがそれでいいのかの判断が私にできないです。どうしたらいいですか？
こちらとしては、それぞれが自分のところの文章を直してコミットするか、 `suggestion` の通りでいいならそのひとがその内容で `suggestion` をコミットするかしてほしいな、と思ってます。

2023-06-24 00:25 UTC, Hiratake commented on src/content/4.support/3.profiles.md
> +- 役割
各ユーザの説明のところは、そのひとがそれでいいのかの判断が私にできないです。どうしたらいいですか？
こちらとしては、それぞれが自分のところの文章を直してコミットするか、 `suggestion` の通りでいいならそのひとがその内容で `suggestion` をコミットするかしてほしいな、と思ってます。

2023-06-24 00:25 UTC, Hiratake commented on src/content/4.support/3.profiles.md
> +- 役割
各ユーザの説明のところは、そのひとがそれでいいのかの判断が私にできないです。どうしたらいいですか？
こちらとしては、それぞれが自分のところの文章を直してコミットするか、 `suggestion` の通りでいいならそのひとがその内容で `suggestion` をコミットするかしてほしいな、と思ってます。

2023-06-24 00:26 UTC, Hiratake commented
全部にコピペしようと思ったけど、めんどかったので普通にコメントします。

各ユーザの説明のところは、そのひとがそれでいいのかの判断が私にできないです。どうしたらいいですか？
こちらとしては、それぞれが自分のところの文章を直してコミットするか、 `suggestion` の通りでいいならそのひとがその内容で `suggestion` をコミットするかしてほしいな、と思ってます。

2023-06-24 03:08 UTC, book000 commented
> ユーザの説明のところは、そのひとがそれでいいのかの判断が私にできないです。どうしたらいいですか？

これについては、Discordでの話し合いの上Discord経由で各運営にその内容で良いか確認を取ります。
確認応答が明日までにない場合、とりあえずそのまま適用します

2023-06-24 03:27 UTC, book000 requested changes

2023-06-24 03:27 UTC, book000 commented on src/content/4.support/3.profiles.md
> +- 管理者
```suggestion
- 鯖破壊者
```

2023-06-24 03:28 UTC, book000 commented on src/content/4.support/3.profiles.md
> +- 管理者
サンプル用で作りましたが無視してください

2023-06-24 04:27 UTC, yuuahp requested changes

2023-06-24 04:27 UTC, yuuahp commented on src/content/4.support/3.profiles.md
> +twitter: yuuaHP_dev
```suggestion
twitter: yuuadev
```

2023-06-24 04:28 UTC, yuuahp commented on src/content/4.support/3.profiles.md
> +twitter: yuuaHP_dev
Twitterのid変えました
https://twitter.com/yuuadev

2023-06-24 05:12 UTC, Omuretsu commented on src/components/content/ContentUser.vue
了解しました。

2023-06-25 02:45 UTC, closed without merging