Linterなどのワークフローの改善
jaoafa/jaoweb4 pull request #155
Opened 2023-06-23 05:07 UTC by Hiratake

[Nuxt のワークフロー](https://github.com/nuxt/nuxt/tree/main/.github/workflows) を参考に `npm scripts` や GitHub Actions のワークフローを書き換えました。

- `**lint` ごとに `lint:**` というスクリプトを作成
- `lint:**` それぞれにファイルの修正を行う `lint:**:fix` スクリプトを追加
- ドキュメントに対して実行するものをまとめた `lint:docs` とそれ以外をまとめた `lint` を設定
- `**lint` という名前ではない `prettier` だけ独立して `format` に設定

GitHub Actions で実行するワークフローに、上記の各 lint をそれぞれ別のジョブとして設定しています。

- `src/content/**` 以下に変更がある場合のみ `textlint` を実行します
- `src/content/**` 以下にしか変更がない場合は ESLint や Stylelint などの CI ワークフローは実行しません

また、 `textlint` について、 `.json` 内にコメントを書くのはよくなさそうなので、拡張子を `.js` に変更しています。（対応してるっぽかったので）
https://textlint.github.io/docs/configuring.html#configuration-files

2023-06-23 05:19 UTC, Hiratake commented
Lint のワークフローがなくなったから、実行されなくてマージできないかも。
このPRがマージされたら設定変更します。（ESLintとStylelintとBuildとTypecheckを必須にする？）

2023-06-23 13:08 UTC, book000 requested changes
もしかしたら後で追加するかもしれないですが、とりあえず。

2023-06-23 22:28 UTC, Hiratake commented on .github/workflows/ci.yml
> +    paths-ignore:
うーん、nuxtのを参考に入れてみたんだけど、ブランチ保護で必須にできないのは困る…
外しましょうか。

2023-06-23 22:28 UTC, Hiratake commented on .github/workflows/docs.yml
> +      - src/content/**
外しましょうか。

2023-06-23 22:29 UTC, Hiratake commented on package.json
> +    "lint:es": "eslint \"**/*.{js,jsx,cjs,mjs,ts,tsx,cts,mts,vue}\"",
`lint` が2回出てくるのもうーんって感じしませんか…？
変更するなら、現行の `lint:script` （ `カテゴリ名:ファイルの種類` ）のほうが良いかな…と思ってますが、いかがでしょう？

2023-06-23 22:30 UTC, Hiratake commented on package.json
> +    "lint:style": "stylelint \"**/*.{css,scss,vue}\"",
`lint:script` にするなら、こちらは `lint:style` かなと思ってます。

2023-06-23 22:48 UTC, Hiratake commented on src/public/site.webmanifest
うーん…
このファイルについては、これまで `prettier` の適用外だったのを、 `prettier` がサポートしているファイルのうち `.md` 以外に適用するように変更して、その後で `npm run format` を実行したので変更されているという状況です。
（インデントやらを揃えない理由もないので）

チームで開発などするときに、エディタに拡張機能を入れてくださいってするのはわりと一般的だと思いますし、それこそ #144 に拡張機能入れてと書いたらいいのでは？と思ってます。 `.vscode/extensions.json` にも入れてますし。

あと、 `npm install` をしない、ドキュメントのみ変更するひとが多い以上、コミット時の `prettier` や `eslint` などがそのひとの環境で動作しないです。なので、そもそもユーザ側でコードスタイルを揃えるというのが難しいのかな、と思いました。
#151 で、 `npm run format` をワークフローで実行する話があると思います。こちらがうまく動くように設定できるようであれば、どのような環境であってもコードスタイルは揃うようになると思いますし、この件を考えるのは #151 がうまくいかなかった場合に…というのではダメでしょうか。

2023-06-23 22:49 UTC, Hiratake commented on package.json
> +    "lint:es:fix": "eslint \"**/*.{js,jsx,cjs,mjs,ts,tsx,cts,mts,vue}\" --fix",
`lint:script:fix` がいいかなと思いますが、どうでしょう？

2023-06-24 02:49 UTC, book000 commented on package.json
> +    "lint:es": "eslint \"**/*.{js,jsx,cjs,mjs,ts,tsx,cts,mts,vue}\"",
まあそうですねえ…。`lint:script` でよさそうです。`lint:script`, `lint:style`, `lint:text` って感じで。

2023-06-24 02:49 UTC, book000 commented on package.json
> +    "lint:style": "stylelint \"**/*.{css,scss,vue}\"",
👍

2023-06-24 02:54 UTC, book000 commented on src/public/site.webmanifest
まあ #151 でうちらのほうで対応できるようになればそこまで問題はない（PR作成→とまちヒラタケformat→PR作成者確認ok→Approveと対応が複数回増える問題はありますが…）ですかねえ。formatを私たちだけでなくPR作成者も実行できるようにする必要がありますね

2023-06-24 02:54 UTC, book000 commented on package.json
> +    "lint:es:fix": "eslint \"**/*.{js,jsx,cjs,mjs,ts,tsx,cts,mts,vue}\" --fix",
👍

2023-06-24 03:17 UTC, Hiratake commented on package.json
> +    "lint:style": "stylelint \"**/*.{css,scss,vue}\"",
じゃあこれは変えなくていいですかね

2023-06-24 03:22 UTC, Hiratake commented on src/public/site.webmanifest
まあ触るひと側でどうにかする設定を追加するなら、 #151 の対応はいらないのでは？ってなるかも。修正する箇所ないだろうし。

2023-06-24 03:23 UTC, Hiratake commented on src/public/site.webmanifest
でも開発環境なんて人それぞれだし、揃えようとしてもうまくできなさそうってなんとなく思っちゃうから、やっぱりworkflowで自動化したほうがいいんか…？

2023-06-24 03:46 UTC, book000 commented on src/public/site.webmanifest
VS Codeを使わずに編集する人（e.g., GitHub UIからの編集）もいるので、片方のチェック処理を入れたからもう片方が不要ってのは違うかなあって感じです。フォームのバリテート処理でフロントにチェックいれたからバックエンドにはいらない！って言ってるのと同じですね

2023-06-24 03:48 UTC, Hiratake commented on src/public/site.webmanifest
まあ一応vscodeの設定にいれときます？あちこちに設定書いてると、変更したときの書き換え忘れとかありそうだなと思ったけど、よく考えたらそもそもそんな書き換えるようなものでもなさそうだし…

2023-06-24 03:49 UTC, book000 commented on src/public/site.webmanifest
まあ私としてはその方がうれしいですねえ。そうすればこちらでのformat処理も不要になるし…。

2023-06-24 03:52 UTC, Hiratake commented on src/public/site.webmanifest
欲しい物どれくらいあるかわからんから足しといて❤

2023-06-24 05:32 UTC, Hiratake commented on package.json
> +    "lint:es": "eslint \"**/*.{js,jsx,cjs,mjs,ts,tsx,cts,mts,vue}\"",
かえました

2023-06-24 05:32 UTC, Hiratake commented on package.json
> +    "lint:es:fix": "eslint \"**/*.{js,jsx,cjs,mjs,ts,tsx,cts,mts,vue}\" --fix",
かえました

2023-06-24 05:33 UTC, Hiratake commented on src/public/site.webmanifest
#161

2023-06-24 05:34 UTC, book000 approved these changes

2023-06-24 05:40 UTC, merged