お問い合わせページの作成
jaoafa/jaoweb4 pull request #159
Opened 2023-06-23 18:13 UTC by Omuretsu

お問い合わせページの作成（旧サイトから移植）と、textlintの対応。
各種リンクは後ほど確認、修正。

2023-06-23 18:15 UTC, Omuretsu commented
Discord`#creater_lab`にも書いたけど、プライバシーポリシーのページ（mdファイル）ってjaoweb4に存在しますか？
探したけど見当たらないです。

2023-06-23 18:16 UTC, Omuretsu reviewed
Discord`#creater_lab`にも書いたけど、プライバシーポリシーのページ（mdファイル）ってjaoweb4に存在しますか？
探したけど見当たらないです。

2023-06-23 23:54 UTC, Hiratake commented
> 探したけど見当たらないです。

つくってください…
当然ですが、まだサイト製作途中なので、存在しないページがたくさんあります。ルールも、まだ全てのページは無いですよね…

2023-06-24 04:13 UTC, book000 requested changes

2023-06-24 04:13 UTC, book000 commented on src/content/4.support/1.inquiry.md
> +また、**上記はMinecraft開発元(Mojang)のお問い合わせ先ではありません。** jao Minecraft Server に関わるお問い合わせについて対応いたします。
```suggestion
また、**上記はMinecraft開発元（Mojang）のお問い合わせ先ではありません。** jao Minecraft Server に関わるお問い合わせについて対応いたします。  
```

textlint、やっぱり太字内とか見出し内の修正してくれないですねえ。うーん。

2023-06-24 04:13 UTC, book000 commented on src/content/4.support/1.inquiry.md
> +- **各種処罰(Ban)の解除申請は [公式Discordサーバ](/blog/join-discord) の#supportチャンネルから行ってください。お問い合わせフォームでは原則として受け付けておりません。**
```suggestion
- **各種処罰(Ban)の解除申請は [公式Discordサーバ](/blog/join-discord) の  `#support` チャンネルから行ってください。お問い合わせフォームでは原則として受け付けておりません。**
```

上の方でインラインコードにしてるので、チャンネル名はインラインコードにしておいたほうがいいかもです

2023-06-24 04:13 UTC, book000 commented on src/content/4.support/1.inquiry.md
> +- jao Minecraft Server は**Java Edition(PC版)向けのサーバです**。Bedrock Edition(iOS, Android, Xbox, Nintendo Switch, Windows 10 Edition)等からはログインできませんのでご注意ください。
```suggestion
- jao Minecraft Server は**Java Edition(PC版)向けのサーバです**。Bedrock Edition（iOS, Android, Xbox, Nintendo Switch, Windows 10 Edition）等からはログインできませんのでご注意ください。
```

2023-06-24 04:34 UTC, Omuretsu commented
> つくってください…
当然ですが、まだサイト製作途中なので、存在しないページがたくさんあります。ルールも、まだ全てのページは無いですよね…

とりあえず #162

2023-06-24 05:58 UTC, book000 approved these changes

2023-06-25 19:37 UTC, book000 requested changes

2023-06-25 19:37 UTC, book000 commented on src/content/4.support/1.inquiry.md
> +公式 Discord サーバ `#support` チャンネルからお問い合わせいただくと、迅速に対応することができます。
```suggestion
公式 Discord サーバ `#support` チャンネルからお問い合わせいただくと、迅速に対応できます。
```

回りくどい気がします。

2023-06-25 19:37 UTC, book000 commented on src/content/4.support/1.inquiry.md
> +以下のページによって、「お問い合わせ内容が解決できないか」をご確認ください。
```suggestion
以下のページにて、「お問い合わせ内容が解決できないか」をご確認ください。
```

動作を示す「によって」よりかは、参照を示す「にて」のほうが良い気がします。

2023-06-25 19:37 UTC, book000 commented on src/content/4.support/1.inquiry.md
> +- [サーバ仕様](/server/specifications)
Markdown として箇条書きの要素ごとを改行で空けるのって良いんですかね？ulタグが独立しそうなものですが、どうなんでしょう（プレビュー確認してません、ごめんなさい！）

2023-08-07 00:07 UTC, closed without merging