feat:プライバシーポリシーの移植と加筆
jaoafa/jaoweb4 pull request #163
Opened 2023-06-24 05:53 UTC by Omuretsu

表題の通り。
close #162

2023-06-24 05:55 UTC, Omuretsu commented on src/content/2.docs/2.policies/2.privacy.md
> +近年のインターネットの普及により、私たちの生活は大きく変わりつつあります。そして、「情報」の持つ価値が高まり、適切な管理が不可欠となってきています。そのために本サービスでは、利用者のプライバシーを尊重し、安全かつ透明なオンライン環境を提供することを目指します。
このあたりを加筆しました。

2023-06-25 09:00 UTC, book000 requested changes

2023-06-25 09:07 UTC, Omuretsu commented on src/content/2.docs/2.policies/2.privacy.md
> +- [Google アナリティクス利用規約](http://www.google.com/analytics/terms/jp.html)
自環境だと正常に表示されますが、URLが変わってリダイレクトされてるって感じですかね？
https://marketingplatform.google.com/about/analytics/terms/jp/

2023-06-25 09:12 UTC, book000 commented on src/content/2.docs/2.policies/2.privacy.md
> +- [Google アナリティクス利用規約](http://www.google.com/analytics/terms/jp.html)
すみません、普通におま環でした…（pi-holeがはじいてた）。まあどっちにしてもリダイレクトするならリダイレクト先を書いたほうが良いかなあって思います。なぜかもともとのやつ `http://` ですしね。

2023-06-25 09:39 UTC, Omuretsu commented on src/content/2.docs/2.policies/2.privacy.md
> +- [Google アナリティクス利用規約](http://www.google.com/analytics/terms/jp.html)
https://github.com/jaoafa/jaoweb4/pull/163/commits/92ceed1795ed49faa04cf10337b8dbd610fafa9e で修正しました。確認をお願いします。

2023-06-25 09:41 UTC, book000 submitted a review, later dismissed

2023-06-25 10:14 UTC, Hiratake requested changes

2023-06-25 10:14 UTC, Hiratake commented on src/content/2.docs/2.policies/2.privacy.md
> +近年のインターネットの普及により、私たちの生活は大きく変わりつつあります。そして、「情報」の持つ価値が高まり、適切な管理が不可欠となってきています。そのために本サービスでは、利用者のプライバシーを尊重し、安全かつ透明なオンライン環境を提供することを目指します。
jao Minecraft Server が提供しているのは Minecraft サーバとか Discord のコミュニティとかなので、「オンライン環境を提供」はなんか違う気がします。
あと、そろそろ「近年の～」は変えたほうがいいような気がします。令和なので。
いい感じの文章、考えてみたけど全然おもいつかんのでアレですが…

2023-06-25 10:14 UTC, Hiratake commented on src/content/2.docs/2.policies/2.privacy.md
> +jao Minecraft Server および関連サービス（以下、「本サービス」と呼びます）は、圧倒的な個性をもつ Minecraft サーバとしての大きな役割を担っていると認識しております。しかし、個人情報の保護に関しては積極的に、誠実に取り組んでまいりたいと思っております。
個人情報の保護は「取り組もうと思ってる」じゃなくて「取り組みます」にしないといけない気がしますね。
また、個人情報の保護に取り組むのは「jao Minecraft Server の運営チーム」だと思いますが、その主語がどこにも入っていなくてよくないのでは？と思いました。
これらを踏まえて、いったん考えてみましたが、どうでしょうか。
```suggestion
jao Minecraft Server 運営チーム (以下「運営チーム」) は、運営チームが運営するサービスをご利用いただくにあたり、コミュニティ参加者のみなさまの大切な個人情報を取り扱っております。  
運営チームでは、このプライバシーポリシーに基づき、個人情報の保護について誠実に取り組んでまいります。
```

2023-06-25 10:43 UTC, Omuretsu commented on src/content/2.docs/2.policies/2.privacy.md
> +近年のインターネットの普及により、私たちの生活は大きく変わりつつあります。そして、「情報」の持つ価値が高まり、適切な管理が不可欠となってきています。そのために本サービスでは、利用者のプライバシーを尊重し、安全かつ透明なオンライン環境を提供することを目指します。
```
デジタル技術の進歩により、「情報」の価値が高まり、その適切な管理が不可欠となってきています。そのために本サービスでは、利用者のプライバシーを尊重し、安全かつ透明なサービスを提供することを目指します。
```

こんな感じでしょうか？
「情報の価値が高まっていること」が、「利用者のプライバシーを尊重すること」の理由になる説明が若干不足してる感がありますが...。

2023-06-25 11:04 UTC, Omuretsu commented on src/content/2.docs/2.policies/2.privacy.md
> +近年のインターネットの普及により、私たちの生活は大きく変わりつつあります。そして、「情報」の持つ価値が高まり、適切な管理が不可欠となってきています。そのために本サービスでは、利用者のプライバシーを尊重し、安全かつ透明なオンライン環境を提供することを目指します。
```suggestion
このような方針を制定する理由は、利用者に安心して本サービスを利用していただくためです。  
デジタル技術の進歩により、「情報」の価値が高まり、その適切な管理が不可欠となってきています。そのために本サービスでは、利用者のプライバシーを尊重し、安全かつ透明なサービスを提供することを目指します。
```

こんな感じでしょうか？
「情報の価値が高まっていること」が、「利用者のプライバシーを尊重すること」の理由になる説明が、若干不足してる感がありますが...。

2023-06-25 15:13 UTC, book000 requested changes

2023-06-25 15:13 UTC, book000 commented on src/content/2.docs/2.policies/2.privacy.md
> +- Minecraft サーバがサーバに保存する情報（ゲーム上における、利用者の位置情報など）
```suggestion
- Minecraft サーバがサーバに保存する情報（ゲーム上における、利用者の位置情報など）
- 利用者がプライベートチャットなどを用いて書き込んだ個人情報（サーバログへ保存されます）
```

個人情報という点で、この置き換えが必要です

2023-06-25 15:13 UTC, book000 commented on src/content/2.docs/2.policies/2.privacy.md
> +- 利用者が導入中の一部 Mod 情報
```suggestion
```

個人情報じゃないので削ってください

2023-06-25 15:13 UTC, book000 commented on src/content/2.docs/2.policies/2.privacy.md
> +- エンダーチェストを含むインベントリ（持ち物）情報
```suggestion
```

個人情報じゃないので削ってください

2023-06-25 15:13 UTC, book000 commented on src/content/2.docs/2.policies/2.privacy.md
> +- 利用者の Minecraft サーバ内での行動情報（ブロックの設置・破壊、チャット内容等）
```suggestion
```

> 利用者がプライベートチャットなどを用いて書き込んだ個人情報

に統合します。

2023-06-25 15:13 UTC, book000 commented on src/content/2.docs/2.policies/2.privacy.md
> +- [Google アナリティクス利用規約](http://www.google.com/analytics/terms/jp.html)
や、これは直ってません。上のURLを直す必要があります（多分間違えて下のリンク先を修正しましたね？）

2023-06-25 17:45 UTC, Omuretsu commented on src/content/2.docs/2.policies/2.privacy.md
> +- [Google アナリティクス利用規約](http://www.google.com/analytics/terms/jp.html)
🥲

2023-06-25 17:48 UTC, Omuretsu commented on src/content/2.docs/2.policies/2.privacy.md
> +- [Google アナリティクス利用規約](http://www.google.com/analytics/terms/jp.html)
https://github.com/jaoafa/jaoweb4/pull/163/commits/f6f90708aeb7d5cae8c9913c6fb5634a189345c6 で修正しました。

2023-06-25 17:49 UTC, Omuretsu commented on src/content/2.docs/2.policies/2.privacy.md
> +近年のインターネットの普及により、私たちの生活は大きく変わりつつあります。そして、「情報」の持つ価値が高まり、適切な管理が不可欠となってきています。そのために本サービスでは、利用者のプライバシーを尊重し、安全かつ透明なオンライン環境を提供することを目指します。
```suggestion
このような方針を制定する理由は、利用者に安心して本サービスを利用していただくためです。  
デジタル技術の進歩により「情報」の価値が高まるなか、プライバシーなどが配慮されるように、情報の適切な管理が不可欠となっています。そのために本サービスでは、利用者のプライバシーを尊重し、安全かつ透明なサービスを提供することを目指します。
```

少し変更。

2023-06-25 19:42 UTC, book000 requested changes

2023-06-25 19:42 UTC, book000 commented on src/content/2.docs/2.policies/2.privacy.md
> +---
```suggestion
author:
  - name: 運営チーム
    icon: /logo.png
---
```

タグはどうしたらいいんですかね…。無理につけなくても良いか…

2023-06-26 16:00 UTC, Omuretsu commented on src/content/2.docs/2.policies/2.privacy.md
> +---
ここに関してはおまかせします。

2023-08-07 00:07 UTC, closed without merging