feat: 処罰方針の移植と加筆
jaoafa/jaoweb4 pull request #165
Opened 2023-06-24 06:15 UTC by Omuretsu

表題の通り。

2023-06-24 06:16 UTC, Omuretsu commented on src/content/2.docs/2.policies/3.bans.md
> +多くの利用者が安心して当サーバを利用できる、楽しいゲーム環境を維持するため、当サーバではこの方針を制定しています。
```
多くの利用者が安心して当サーバを利用できる、楽しいゲーム環境を維持するため、当サーバではこの方針を制定しています。  
```
この部分を加筆。

2023-06-24 06:17 UTC, Omuretsu commented on src/content/2.docs/2.policies/3.bans.md
> +運営は [サーバルール](/server/rules) や [各種方針](/server/policies) を根拠に、当該プレイヤーに対して適切な処罰を行います。
ルールと方針に関する方向性が決まらないと、ここは修正できないです。

2023-06-24 06:18 UTC, Omuretsu commented on src/content/2.docs/2.policies/3.bans.md
できれば、処罰の内容について表を作りたい。

2023-06-25 19:30 UTC, book000 requested changes
処罰一覧部分はまあ表などにした方がいい気がするんで、そこはとりあえずレビューしませんでした。

2023-06-25 19:30 UTC, book000 commented on src/content/2.docs/2.policies/3.bans.md
> +title: 各種処罰方針
```suggestion
title: 処罰方針
```

「各種」、抜いてもいいかもしれません

2023-06-25 19:30 UTC, book000 commented on src/content/2.docs/2.policies/3.bans.md
> +このページでは、jao Minecraft Server（以下、「当サーバ」といいます）における各種禁止処置（処罰・Ban）について記載します。
```suggestion
このページでは、jao Minecraft Server（以下、「当サーバ」といいます）における処罰について記載します。  
```

処罰で統一しましょう。Ban⊃処罰なので、併記しなくて良いです。

2023-06-25 19:30 UTC, book000 commented on src/content/2.docs/2.policies/3.bans.md
> +公式 Discord サーバにおける運営・処罰方針については、[こちら](server/rules/discord) をご確認ください。
適用範囲を明確化したいところです。建築についてのルールのように、「このルールは、以下に適用されます。」の書き方に統一した方がルール以下の統一性があってよさそうです
see: https://github.com/jaoafa/jaoweb4/blob/main/src/content/2.docs/1.rules/1.build.md

2023-06-25 19:30 UTC, book000 commented on src/content/2.docs/2.policies/3.bans.md
> +---
```suggestion
tag:
  - Minecraft
author:
  - name: 運営チーム
    icon: /logo.png
---
```

タグと作者情報あったほうがいいかもです。

2023-06-25 19:30 UTC, book000 commented on src/content/2.docs/2.policies/3.bans.md
> +当サーバにおける各種禁止処置は、「**当該ユーザが悪意をもって、サーバや他プレイヤーに対して迷惑行為をした**」と運営が判断した場合に行います。
```suggestion
当サーバにおける処罰は、「**当該ユーザが悪意をもって、サーバや他プレイヤーに対して迷惑行為をした**」と運営が判断した場合に行います。  
```

2023-06-25 19:30 UTC, book000 commented on src/content/2.docs/2.policies/3.bans.md
> +迷惑行為とは、具体的に以下の事例を指します。
```suggestion
迷惑行為とは、具体的に以下の行為を指します。
```

事例でもいいんですが、「迷惑行為」の具体的な内容なので「行為」でよい感じがします

2023-06-25 19:30 UTC, book000 commented on src/content/2.docs/2.policies/3.bans.md
> +- チャットでの暴言、性的発言、その他迷惑行為
迷惑行為の具体例なのに、「迷惑行為」で終わらせてるの良いんですかね？「人が嫌な気持ちになる行為」とか具体化した方がいい気がします。「人が嫌な気持ちになる行為」って言葉が適切かイマイチですが

2023-06-25 19:30 UTC, book000 commented on src/content/2.docs/2.policies/3.bans.md
> +運営は [サーバルール](/server/rules) や [各種方針](/server/policies) を根拠に、当該プレイヤーに対して適切な処罰を行います。
まあ、ルールはユーザに対して「守ってくれよな！」ってものだし、方針は「運営の判断根拠」なので、どうあれこの文章で良いかなと思います。別案ありましたら是非。

2023-06-25 19:30 UTC, book000 commented on src/content/2.docs/2.policies/3.bans.md
> +なおその際は当該ユーザの、当サーバ内で過去に実行された処罰履歴や、MCBans に登録されている他サーバの処罰履歴を照会する場合があります。
```suggestion
なおその際は当サーバ内で過去に実行された処罰履歴や、他サーバの処罰履歴を照会する場合があります。
```

「当該ユーザの」は自明で回りくどいので外していいかと。
MCBans以外の処罰履歴（Wikiにずらずら書いてるようなサーバとか）も参考にする時があるので、この縛りは外させてください。

2023-06-25 19:30 UTC, book000 commented on src/content/2.docs/2.policies/3.bans.md
> +**※この処罰は「各種禁止処置」には含まれませんが、便宜上ここで解説しています。**
```suggestion
**※この処罰は「禁止処置」には含まれませんが、便宜上ここで解説しています。**
```

全体的に各種が不要な感じがするので、取っ払ってしまいましょう

2023-06-25 19:46 UTC, Omuretsu commented on src/content/2.docs/2.policies/3.bans.md
> +- チャットでの暴言、性的発言、その他迷惑行為
https://github.com/jaoafa/jaoweb4/pull/165/commits/4d1d63b5ed11da549779cd32495ce880beab49b1 で修正しました。

2023-06-25 19:47 UTC, Omuretsu commented on src/content/2.docs/2.policies/3.bans.md
> +迷惑行為とは、具体的に以下の行為を指します。
ここに、「通信機器の機能を妨害し、または制限する情報を発信する行為」みたいな文面って入れるべきでしょうか？

2023-06-25 19:47 UTC, book000 commented on src/content/2.docs/2.policies/3.bans.md
> +- チャットでの暴言、性的発言、その他迷惑行為
👍

2023-06-25 19:49 UTC, Omuretsu commented on src/content/2.docs/2.policies/3.bans.md
> +公式 Discord サーバにおける運営・処罰方針については、[こちら](server/rules/discord) をご確認ください。
書くとしたら
`・Minecraftサーバや公式Discordサーバなど、当サーバの運営が提供するサービス`
を適用範囲にすればいいですかね...?

2023-06-25 19:50 UTC, book000 commented on src/content/2.docs/2.policies/3.bans.md
> +迷惑行為とは、具体的に以下の行為を指します。
文章が難しくて何のことを定義してるのかよくわかりません。
コンピュータウイルスの配布とか？

2023-06-25 19:53 UTC, book000 commented on src/content/2.docs/2.policies/3.bans.md
> +公式 Discord サーバにおける運営・処罰方針については、[こちら](server/rules/discord) をご確認ください。
や、このページはあくまでMinecraftサーバ内で適用される処罰（EBan, ChatBan, VBan）について定義しているのでDiscordは無関係なので適用範囲は `Minecraft サーバの利用` かなと思います。利用ってざっくりしてていいのかよくわかりませんが。

（実のところ、Discord鯖側ではVBanされたユーザは参加不可になるので、無関係でもないのですが…）

2023-06-25 19:53 UTC, Omuretsu commented on src/content/2.docs/2.policies/3.bans.md
> +迷惑行為とは、具体的に以下の行為を指します。
・Minecraftサーバ内でのクラッキング、Modなどの悪用
・Discordサーバ内での、Botなどの悪用
・Discordサーバ内などでの、ウイルスの配布

あたりを想定していました。
ちょっと長くなるけど、定義しておいたほうがいい気がしまして...。

参考（SNSガイドラインだけど）: https://www.yakult-swallows.co.jp/pages/company/sns

2023-06-25 19:57 UTC, Omuretsu commented on src/content/2.docs/2.policies/3.bans.md
> +公式 Discord サーバにおける運営・処罰方針については、[こちら](server/rules/discord) をご確認ください。
Discord側で超絶迷惑行為を働いて、マイクラ鯖側で二次的にBanする可能性もあるので、そこはなんともな気がします。
（Discordルールを根拠として、マイクラ鯖側でも処罰するよ、って文章が欲しい。今ないよね？）

2023-06-25 20:08 UTC, book000 commented on src/content/2.docs/2.policies/3.bans.md
> +公式 Discord サーバにおける運営・処罰方針については、[こちら](server/rules/discord) をご確認ください。
難しいところです。
VBanの説明箇所でDiscordルールを根拠とした処罰を含むってして、免責事項に相互で包括的に処罰を行うみたいな記述を書くとか？
少なくともこのページ内の内容が直接的にDiscordでの処罰に繋がることはない（荒らした→VBan→Discord Banはあっても、荒らした→Discord Banはない）ので、適用範囲としてはMinecraftサーバオンリーで良いと思っています。

2023-06-25 20:14 UTC, book000 commented on src/content/2.docs/2.policies/3.bans.md
> +迷惑行為とは、具体的に以下の行為を指します。
特殊例すぎて「その他、運営が不適切だと判断する行為」でまとめさせて欲しい感じですね…。
そもそも、クラッキングはさておき悪用ってのが曖昧すぎます。悪用の結果として「他人の建築物を許可なく破壊・編集する行為」とか「アイテムやコマンドを用いた、他ユーザへの嫌がらせ行為」とかに繋がるのであれば処罰対象ですし。

あえていじるなら、チャットでのコンピュータウイルスとか不審サイトへの誘導が明確化されてないので、これらについての記述があってもいいかもしれません。

2023-06-25 20:18 UTC, Omuretsu commented on src/content/2.docs/2.policies/3.bans.md
> +迷惑行為とは、具体的に以下の行為を指します。
そもそもが`処罰方針`なので、「各種方針で規制されている行為」を処罰対象とする

っていう感じでいいですかね？
そうしたらルールと方針があまり変わらないモノになってしまう感はあるけど...　

2023-06-25 20:19 UTC, Omuretsu commented on src/content/2.docs/2.policies/3.bans.md
> +迷惑行為とは、具体的に以下の行為を指します。
> あえていじるなら、チャットでのコンピュータウイルスとか不審サイトへの誘導が明確化されてないので、これらについての記述があってもいいかもしれません。

現行のチャットガイドライン内に存在してないですね。加筆しましょう。

2023-06-25 20:29 UTC, book000 commented on src/content/2.docs/2.policies/3.bans.md
> +迷惑行為とは、具体的に以下の行為を指します。
> そもそもが処罰方針なので、「各種方針で規制されている行為」を処罰対象とする

方針は運営としての方針なので、「ルールで禁止・制限していることに違反したユーザに対して処罰する」「処罰にあたり、どの処罰を適用するか」ということを示すものがこの処罰方針です。方針にはユーザを規制する事項を書くことはできません（それらはルール化されるべき）。

となると、迷惑行為を定義するのはルール側ってことになりますよね…。ここで書くべきじゃないってことです（そのまま移植はダメそうですね…）

2023-06-26 09:10 UTC, Omuretsu commented on src/content/2.docs/2.policies/3.bans.md
> +迷惑行為とは、具体的に以下の行為を指します。
> となると、迷惑行為を定義するのはルール側ってことになりますよね…。ここで書くべきじゃないってことです（そのまま移植はダメそうですね…）

🥲🥲🥲

2023-06-26 10:15 UTC, book000 commented on src/content/2.docs/2.policies/3.bans.md
> +迷惑行為とは、具体的に以下の行為を指します。
まあ突き放すだけだと流石に良くないので、改善策をいくつか。

- 「迷惑行為とは、具体的に以下の行為を指します。」にある4点を、ルール以下で定義する必要があります。
- 基本方針は既存の最初2文は残し、「迷惑行為と判断するのはルール内で禁止している事項」を明文化すると良いと思います。もっと改善するのであれば、迷惑行為という単語を用いずに、「ルール内で禁止している事項を悪意を持って行った場合は処罰対象になる」としても良いかもしれません。
- [基本ルール](https://jaoweb.pages.dev/docs/rules) 内で「他の参加者の迷惑になる行為をしないこと」があるので、正直大抵の事柄はこれで賄えると思います。逆に、他の利用者は迷惑だと感じるたら早い段階で「迷惑です」という意思表示が必要ですね。
- なんにせよ、何でもかんでもjaoweb2からそのまま移植するのは正直この作業の本意ではありません。古い陳腐化した文章を排除したり、より読みやすい・見やすい文章やページ構成になるような改良ないし作り直しが必須です。ルールページも大規模に変更されてますしね。

2023-06-26 15:42 UTC, Hiratake commented on src/content/2.docs/2.policies/3.bans.md
> +公式 Discord サーバにおける運営・処罰方針については、[こちら](server/rules/discord) をご確認ください。
そもそも「運営方針」なので、運営チームがこういうふうに運営していきますっていうものだという認識です。
なので、適用範囲は運営チームのメンバーの行動ではないでしょうか…

2023-06-26 23:25 UTC, book000 commented on src/content/2.docs/2.policies/3.bans.md
> +公式 Discord サーバにおける運営・処罰方針については、[こちら](server/rules/discord) をご確認ください。
まあ処罰って、「運営がやるもの」だけど結果として利用者に反映されるものなんでなんとも言えないですよね。それの方針なんで、方針以下に置いた方がいいのだけど。

別のconversationでも多少触れているけど、「運営の判断基準や行動指針」は「運営方針」だけど、「具体的に利用者がどんなことをしたらいけないのか」は「ルール」だと思っています。したがって、運営が持つ武器（処罰のことを武器と言っていいかは微妙だけど…）はEBan, ChatBan, VBanであって、それを振りかざすのは「ルール」に違反したときで（=これを方針に書くべき）、その武器が振りかざされた結果として利用者に対してどんなことがもたらされるのかについては方針なんですかねえ

2023-06-26 23:29 UTC, book000 commented on src/content/2.docs/2.policies/3.bans.md
> +公式 Discord サーバにおける運営・処罰方針については、[こちら](server/rules/discord) をご確認ください。
で、適用範囲については「じゃあ運営はどんな場所でこの処罰を行うの？」って話が中々分かりにくいから指摘したんです。これらの処罰はMinecraft鯖内だけであって、Discordでは直接的に行われるわけではない（Discordの中でEBanというものはないので）。したがって、「このページで記載している事項ってのはMinecraftサーバのみに適用されるものですよ」ってのがきちんとわかりやすく書かれていなければ、読む側にとって不親切では？ってところです

2023-06-26 23:34 UTC, book000 commented on src/content/2.docs/2.policies/3.bans.md
> +公式 Discord サーバにおける運営・処罰方針については、[こちら](server/rules/discord) をご確認ください。
他のページでもいえるかもしれませんが、「jao Minecraft Server」という言葉がどこに掛かるのかって不定なんですよね。MinecraftやDiscordをまとめたコミュニティのことを指せば、Minecraftサーバそのものを指すこともある。もともとのこの書き方では、1行目の「jao Minecraft Server」がどういう形の形態を指しているかわからないんですよね

2023-06-27 16:29 UTC, Omuretsu commented on src/content/2.docs/2.policies/3.bans.md
> +迷惑行為とは、具体的に以下の行為を指します。
時間があるときにゆっくり考えます。

2023-08-07 00:08 UTC, closed without merging