feat: 他ページへの埋め込み表示機能追加
jaoafa/jaoweb4 pull request #44
Opened 2023-03-12 22:10 UTC by book000

- close #30 

`:content-embed{url="https://jaoafa.com/server/beginners"}` のような形でコンポーネントを指定すると指定した URL の埋め込みコンテンツが表示される機能を追加しました。
ただ、元々の issue で期待していた「URL を張るだけで埋め込みコンテンツが表示される」形ではないので、できれば改善したいところです。（`@nuxt/content` で Markdown のパース時に挙動を追加するような何か…な気がするのですが、よくわかっていません）

フロントのデザイン部分については追加での変更が必要だろうと思いますので、適宜コミットを投げていただけたら。
特に、「サムネイルのクリップ位置が気持ち悪い」のと「説明文の切り捨てなどレスポンシブ対応があまりできていない」、「コンテンツの高さが高すぎる」点は気になっています。

バックエンドのコードも気に入らなかったらいじってください。

開発環境で動作させているときに Markdown ファイルをいじると `/api/embed` からのレスポンスが不適切で `Failed to fetch data.` が表示されます。
これはホットリロード時にエンドポイントにリクエストを飛ばしているせいなので、ホットリロードが済んでからリクエストを飛ばすようになれば良いのですが…よくわかっていません。

よろしくお願いします。

2023-03-12 22:57 UTC, Hiratake commented on package.json
> +    "ogp-parser": "0.6.0",
セキュリティ云々でてるから変えたほうがいいかもだけど、generateするなら関係ないかも？

2023-03-12 22:59 UTC, Hiratake requested changes

2023-03-12 22:59 UTC, Hiratake commented on src/components/content/ContentEmbed.vue
> +  <div v-else>
データが取得できなかったという情報は、記事を見に来てるひとには不要ではと思うので、取れなかったら何も出さないほうがいいかも。

2023-03-12 23:00 UTC, book000 commented on src/components/content/ContentEmbed.vue
> +  <div v-else>
「以下の記事をご覧ください」のあとに何も表示されてないと意味不明だから、URLだけリンクにして表示するのが適切かしら？

2023-03-12 23:02 UTC, book000 commented
そもそもよくよくかんがえたらこのカード、リンク化してないですね

2023-03-12 23:03 UTC, Hiratake commented on src/components/content/ContentEmbed.vue
> +  <div v-else>
あーそういう使い方をするのか。
普通に文章中入れてあるリンクを、分かりやすいようにその段落の下に、記事執筆者が任意でembed表示できるようにするのかと思ってた

2023-03-12 23:04 UTC, Hiratake commented
たしかに

2023-03-12 23:05 UTC, book000 commented on src/components/content/ContentEmbed.vue
> +  <div v-else>
本当は文章中にURL張ったらそれがembedになってくれる挙動のほうがいいんですけどね。イメージとしてはこんな感じ (画像の記事は [これ](https://zenn.dev/book000/articles/set-output2github-output))

![image](https://user-images.githubusercontent.com/8929706/224579357-9de828b8-18b9-4e0c-a9be-12166a416147.png)

![image](https://user-images.githubusercontent.com/8929706/224579416-557eb957-117d-427c-83ae-deff5c723239.png)

2023-03-12 23:09 UTC, Hiratake commented on src/components/content/ContentEmbed.vue
> +  <div v-else>
なるほど
データ取れなかったときはURLそのまま出すとかが良きかもだねえ

2023-03-12 23:16 UTC, book000 commented on package.json
> +    "ogp-parser": "0.6.0",
ちょっとogp-parserに依存しない形に書き換えます

2023-03-12 23:19 UTC, Hiratake commented on package.json
> +    "ogp-parser": "0.6.0",
圧倒的感謝

2023-03-12 23:45 UTC, book000 commented
以下の変更を加えました。

- カードのリンク化をしました
- ogp-parser に依存せず Fetch API を利用して独自にメタタグを取得するようにしました。

2023-03-12 23:45 UTC, book000 commented on package.json
> +    "ogp-parser": "0.6.0",
修正しましたので確認のうえ問題なければクローズください

2023-03-12 23:45 UTC, book000 commented on src/components/content/ContentEmbed.vue
> +  <div v-else>
修正しましたので確認のうえ問題なければクローズください

2023-03-12 23:49 UTC, book000 commented
> 文章中にURL張ったらそれがembedになってくれる挙動

この辺のフック処理なんでしょうけど、URL regexにマッチするもの見つけてそれにコンポーネントを置き換えるってどうやってだよ…感ですねえ

https://content.nuxtjs.org/api/advanced

2023-03-13 06:09 UTC, book000 commented
いろいろ調べた感じ、`content:file:afterParse` 時にコンテンツの親子情報見ながら対象のオブジェクトを `{ "tag": "content-embed" }` みたいなやつに置き換えればうまくいくのかも。中々泥臭いけど…

2023-03-13 09:42 UTC, book000 commented
以下の変更を加えました

- URLをそのまま貼り付けても埋め込みコンテンツ化されるようになりました

![image](https://user-images.githubusercontent.com/8929706/224664416-1a5775f0-decf-4947-85d3-feff516690c8.png)

2023-03-13 09:56 UTC, book000 commented
- Fetch API のリダイレクトはデフォルトが `follow` らしいので引数を消しました。参考: https://developer.mozilla.org/ja/docs/Web/API/fetch

2023-03-13 10:01 UTC, book000 commented
- `Response.ok` をなんも見ていない問題を修正

2023-03-13 18:38 UTC, book000 commented
@Hiratake ヒラタケがいじってもらったフロントデザイン部分、確認して問題ありませんのでレビューお願いします。

2023-03-14 15:05 UTC, Hiratake approved these changes

2023-03-14 15:05 UTC, merged

2023-03-14 15:07 UTC, Hiratake commented
🙏