ルールの文章を追加
jaoafa/jaoweb4 pull request #67
Opened 2023-03-26 08:42 UTC by Hiratake

ルールの文章を追加するPRです。
余白とか見た目とか表示とかの調整とかは別ブランチで後からやるので、とりあえず内容だけに絞って考えていければ。

2023-03-26 08:43 UTC, Hiratake commented
とりあえずルールのインデックスページの文章をざっくり書きました。
他のページもざっくり書いたらコミットしてあげていくので、時間あるときに見たり直したり、代わりに書いたりしていただければ。

2023-03-26 09:10 UTC, book000 requested changes
必ず変更しろというものではありませんが…。のちのち変える形でもいいです
適当にスパ入りながら見たので後でレビュー追加するかも

2023-03-26 09:10 UTC, book000 commented on src/content/2.docs/1.rules/index.md
> +既にコミュニティへご参加いただいている方は、お時間のあるときに読み返していただき、より良いコミュニティをつくっていくためにご意見などいただければと思います。
どこで？という話が一文あってもいいかも。公式Discordサーバの#support?

2023-03-26 09:10 UTC, book000 commented on src/content/2.docs/1.rules/index.md
> +- MinecraftサーバやDiscordサーバからのキック・BANなどの処罰
(後から追加でもいいけど、)処罰方針に沿って処罰します的な文章かな？どんな処罰が課されるのかは明示化したほうがよさそう

2023-03-26 09:10 UTC, book000 commented on src/content/2.docs/1.rules/index.md
今まで書いてた「システムによって制限されている行為」とかはどこに書こうかしら？

2023-03-26 09:15 UTC, Hiratake commented on src/content/2.docs/1.rules/index.md
ルールのトップページに全部書いたほうが良いという意見？
`rules` なので、配下に別のページがいくつか出来るわけなので、そっちに書けばいいと思いますが。

2023-03-26 09:16 UTC, Hiratake commented on src/content/2.docs/1.rules/index.md
1ページに全部まとめるなら、こないだ話してたような気もするけど `rules` から `rule` にしますが。

2023-03-26 09:19 UTC, Hiratake commented on src/content/2.docs/1.rules/index.md
> +既にコミュニティへご参加いただいている方は、お時間のあるときに読み返していただき、より良いコミュニティをつくっていくためにご意見などいただければと思います。
とくに場所は決めなくてもいいのでは？
前に話してたとおり、コミュニティ全体でルールとかについて考えていきたい的なのがあるので、supportだとそれは運営との話し合いにしかならないので。

2023-03-26 09:19 UTC, Hiratake commented on src/content/2.docs/1.rules/index.md
> +既にコミュニティへご参加いただいている方は、お時間のあるときに読み返していただき、より良いコミュニティをつくっていくためにご意見などいただければと思います。
場所を決めるとすれば、DiscordにForumチャンネル作るとかがいいのかねえ。

2023-03-26 09:22 UTC, Hiratake commented on src/content/2.docs/1.rules/index.md
> +- MinecraftサーバやDiscordサーバからのキック・BANなどの処罰
> 処罰方針に沿って処罰します的な文章

たしかにそんな感じにしたほうがいいかも。
ルールを守っていただけない場合、なんか処罰についての方針が書いてあるページの内容に沿って以下のような対応をするかも、みたいな。

2023-03-26 09:25 UTC, Hiratake commented
一緒に内容作っていくんだから、reviewerにいれるの違うなと思って外したんだけど、一回reviewerに入れてしまったのでレビューさせてしまったかも。申し訳ない。

2023-03-26 10:12 UTC, book000 commented on src/content/2.docs/1.rules/index.md
> +既にコミュニティへご参加いただいている方は、お時間のあるときに読み返していただき、より良いコミュニティをつくっていくためにご意見などいただければと思います。
場所決めないと言う側はどこで？ってなりがちになるので、まあきちんと決めといたほうがいいかもね。フォーラムチャンネル作ってもいいし

2023-03-26 10:15 UTC, book000 commented on src/content/2.docs/1.rules/index.md
全部をindexに書くのではなくて、Minecraft、Discord限らず適用される「サーバルール（コミュニティルール？）」をなにかしら規定しなきゃならなそうとは思っている。
そういうのをindexに書いてもいいし、コミュニティルールとして独立ページにしてもいいかな

2023-03-26 10:15 UTC, book000 commented on src/content/2.docs/1.rules/index.md
コミュニティルールとするのは、いまの/server/rules/index.mdの中身だと思うけども。

2023-03-26 10:16 UTC, book000 commented
通知設定的にレビュアー刺してくれたほうが必ず確認するので、むしろ刺してくれたほうが有り難いかも。

2023-03-26 10:25 UTC, Hiratake commented on src/content/2.docs/1.rules/index.md
Minecraft、Discord限らず適用されるルールをindex.mdにつくって、配下には「Minecraftルール」「Discordルール」みたいなサービスごとのルールを作るということ？

2023-03-26 10:33 UTC, Hiratake commented on src/content/2.docs/1.rules/index.md
まだちゃんと作れてないけど、サービスごとじゃなくて、分類？種類？ごとにページわけるものだと思ってた。

![image](https://user-images.githubusercontent.com/23224932/227769960-9fb43b52-ac05-4e17-a7d1-589c8e19da46.png)

2023-03-26 10:40 UTC, book000 commented on src/content/2.docs/1.rules/index.md
まあ、うーん。どういうのが見やすいかしらね。
ルール分類ごとにページ作ってサービスごとに適用されうるルール一覧とか？記事にタグ付けできてもいいかも。

少なからず、「全サービスに適用されるルール（他人の迷惑になる行為、明示的に制限されている行為、サービス提供に支障の出る行為、他者が明らかに不快に感じている行為を続けること）」はあるから、これが全体的に適用されますよ！ってのがrules/indexを見ただけの人でも分かってもらえるような構成にしたいかな、とは思います。それをコミュニティルールとして独立ページにしてもいいし、rules/indexに書いてもいいし。

2023-03-26 10:43 UTC, Hiratake commented on src/content/2.docs/1.rules/index.md
その「全サービスに適用されるルール」がどれくらいの分量になるかによる気がします。めちゃくちゃ長くなるようだったら、まずルールのトップページ開いただけで読む気がなくなるだろうし…

2023-03-26 10:49 UTC, Hiratake commented on src/content/2.docs/1.rules/index.md
> +- MinecraftサーバやDiscordサーバからのキック・BANなどの処罰
ルールに沿ってなのかルールに従ってなのかルールに則ってなのか、日本語わからんをしちゃうわね

2023-03-26 10:49 UTC, Hiratake commented on src/content/2.docs/1.rules/index.md
> +- MinecraftサーバやDiscordサーバからのキック・BANなどの処罰
ルールじゃなくて方針

2023-03-26 10:51 UTC, Hiratake commented on src/content/2.docs/1.rules/index.md
> +- MinecraftサーバやDiscordサーバからのキック・BANなどの処罰
処罰方針に基づいて？

2023-03-26 11:51 UTC, Omuretsu approved these changes

2023-03-26 12:31 UTC, book000 commented on src/content/2.docs/1.rules/index.md
> +- MinecraftサーバやDiscordサーバからのキック・BANなどの処罰
```text
ルールをお守りいただけない場合、[処罰方針](...) に則り処罰を行う場合がございます。
```

かなあ。「場合がございます」ってぼやかしているのは運営が認識できなかった場合は処罰できないから...

2023-03-26 12:36 UTC, book000 commented on src/content/2.docs/1.rules/index.md
まあ、禁止事項として `他人の迷惑になる行為`, `明示的に制限されている行為`, `サービス提供に支障の出る行為`, `他者が明らかに不快に感じている行為を続けること`, `再利用の禁止` の4つは必須かなあ。遵守事項は `自分の行動に責任をもつ（アカウントで行われた行為はそのアカウントの所有者による行為とみなす）` くらい？[現行のサーバルール](https://jaoafa.com/server/rules) を見る感じ。

2023-03-26 14:26 UTC, Hiratake commented on src/content/2.docs/1.rules/index.md
禁止事項と遵守事項に分ける理由が、個人的には特に無いのでまとめて「ルール」でいいと思ってます

> 明示的に制限されている行為

じゃあ明示的に書かれたりしてないことはやっていいのか？って話になりそうなので、書かないほうがいいかも？

> 他者が明らかに不快に感じている行為を続けること

迷惑になる行為とまとめてもいいかも？

> 再利用の禁止

これは元の建築物とか創作物とかの作者が許可してたり迷惑に感じてないのなら問題ないと思うので、全体に絶対適用されるものとして書くのはよくないかも。
特に、Discordで他人の発言をコピペして繰り返す文化がある中でこれやると、そういうことも規制対象になってしまわない？迷惑になる行為に含めてしまっても良いような気がしてます。

2023-03-26 14:26 UTC, Hiratake commented on src/content/2.docs/1.rules/index.md
ルールのメインページが物凄い分量あると、初手から圧倒されて読まない人が余計に増えそうなので、できる限り短くor他のページに分割したいと思ってます。

https://note.com/mss_discord/n/n59ae4ccb8140#26fc3c20-e352-4eda-835f-ead5ba0b2f9d
このへん参考にしてるんだけど、ルールのメインページが「簡易版ルール」、配下のページが「免責の為のルール」のイメージをしてます。

2023-03-26 14:43 UTC, Hiratake commented on src/content/2.docs/1.rules/index.md
> +- MinecraftサーバやDiscordサーバからのキック・BANなどの処罰
どんな荒らし行為・迷惑行為がなされるかは分からんし、全部想定しきれないので、○○が起こったら✕✕という処罰をするっていうのを全部書くことは不可能だと思ってます。（どんな処罰を行うかは例をいくつかあげるとかは出来ると思うけど）

色々調べたけど、
https://www.nihongo-appliedlinguistics.net/wp/archives/7883#outline_1__3_1
処罰方針には、方向性が書いてあるはずなので（方針なので）、沿ってが正しいような気がするかも？

2023-03-26 15:15 UTC, Hiratake commented
文章をいろいろ直してみるなどしました。

2023-03-26 19:38 UTC, book000 commented on src/content/2.docs/1.rules/index.md
> +- MinecraftサーバやDiscordサーバからのキック・BANなどの処罰
たしかに確実な遵守性というよりかは方向性が正しそうだなあ。その場合「〜沿って」だねえ

2023-03-26 20:09 UTC, book000 commented on src/content/2.docs/1.rules/index.md
(一通り書いた後で ea171ea3171e977b9556739c2a324cf720759850 のコミットに気づいたので、かぶっていたらごめんなさい。)

> じゃあ明示的に書かれたりしてないことはやっていいのか？

正直いうと、これは「（他のルールに違反し得ない限り）はい」です。
文書による禁止行為とシステム的な制限行為（=主に権限による制限措置）で禁止及び制限しているもの以外の行為もやっていけないとなると、流石に何をしていいのかが微妙になりすぎます。
運営や他ユーザとして明らかに不快で迷惑な行為だとその場で思うのなら、明確な警告を出すことで後述される「他者が明らかに不快に感じている行為を続けること」に反するので、これもカバーできます。

現状の意図的に明文化していない運営内のなんとなくの処罰方針として、「軽い一犯程度なら許す（≒解除も視野）」があるので、下手に書かないで曖昧とするよりかは「（MyMaid4などの）システムが制限してきたらやめてくれ」とする方がユーザサイドとしてもわかりやすいんじゃないかなと思っています。

まあ少なくとも「システムが制限することを、その制限を無視して/回避して行う」のを明確に禁止したいです。

> 迷惑になる行為とまとめてもいいかも？

見出し分けの観点としてまとめることはいいけど、「他のユーザがやめてくれと言ったこと」を続けるような行為を禁止することを明確に記述したいなあとは思います。

> Discordで他人の発言をコピペして繰り返す文化がある中でこれやると、そういうことも規制対象になってしまわない？

これは...まあそうですね...

「迷惑な行為」がどうしても広くなりがちなので、どう書いたら読み手として読みやすく禁止する行為としてカバーできるか難しいなあと思います。

> 初手から圧倒されて読まない人が余計に増えそうなので、できる限り短くor他のページに分割したいと思ってます。

これは同意見です。indexからどうわかりやすく誘導するかはよく考えないととは思いますが...。どのサービスや機能を使う時はこれが適用される、という一覧表があってもいいかもしれないなあと思っています。

2023-03-26 20:20 UTC, book000 reviewed
Request changesではなくCommentとして。

2023-03-26 20:20 UTC, book000 commented on src/content/2.docs/1.rules/index.md
> +基本のルールは、以下のとおりです。
細かいところですみません。なんか違和感を感じます。なんでだろう...?

```suggestion
基本となるルールは、以下のとおりです。
```

2023-03-26 20:38 UTC, Hiratake commented on src/content/2.docs/1.rules/index.md
> +基本のルールは、以下のとおりです。
なんでと言われても…
でもそっちのがいいかも。

2023-03-26 21:00 UTC, Hiratake commented on src/content/2.docs/1.rules/index.md
システム側で制限して、仕組みとしてそもそもできないようにするってのは理想的だとは思うけど、、

システムを縮小しようって話もしてて、今後対応していけるかどうかも分からん状態で、システムで制限してることはやらないでって意図のルールを入れるのはこわいかも。
システムを全部任せっきりになってるせいなので、申し訳ないけど…（引き継いだりできるように色々勉強するつもりではいます）

運営側が制限していることをやろうとするのは、サービス提供に支障の出る行為に含まれませんか？

2023-03-26 21:45 UTC, book000 commented on src/content/2.docs/1.rules/index.md
> システム側で制限して、仕組みとしてそもそもできないようにするってのは理想的だとは思うけど、、
> システムを縮小しようって話もしてて、今後対応していけるかどうかも分からん状態で、システムで制限してることはやらないでって意図のルールを入れるのはこわいかも。

全部をシステムレベルで制限するのは不可能なので、それですべてを覆う気はないです。なのでシステマティックでなく人間が判断する項目として「他者が明らかに不快に感じている行為を続けること」で補完しようとしています。
システム的な対応を縮小するからというより、結果として「権限プラグインとかによる制限を適用できない」のは流石に微妙かと。私が管轄するシステム全てを取っ払ったとしても、権限管理プラグインは残ります。

項目を減らして他の項目に合算しようとするのは明確性のない文章になるので（それを別ページで補充するならともかく）、あんまり賛成し難いところです。
さっき引用していたページの以下に戻ってしまうようなルール構成は逆に運営負担が増える原因になるのでは？と思っています。

> 「運営の免責を行いやすい」「アクシデント時の対処の幅が広い」など、運営者目線でメリットのあるルール構造であった為、多くのコミュニティで採用されておりました。

https://note.com/mss_discord/n/n59ae4ccb8140

繰り返しになりますが、文章を減らすために消した説明文を別ページで補充するのであれば良いですが、だったらindexで「このページは必ず見てね」で誘導したほうが項目が二重にならずに済みそうです。
※つまり現行のPRの「箇条書きで項目を並べるだけ並べて、各項目に対してどんなことがダメなのかの詳細な説明をしない」のはあんまり賛同し難いところです。詳細性がなく、運営もユーザも判断しにくいルールになるので…。

2023-03-26 21:52 UTC, Hiratake commented on src/content/2.docs/1.rules/index.md
前でも書いてますが、「ルールのメインページが「簡易版ルール」」という認識なので、下のページで詳細を書く想定でいます。（現行のPRにも、詳細は各ページを確認してという文章を入れています）

2023-03-26 21:54 UTC, Hiratake commented on src/content/2.docs/1.rules/index.md
箇条書きにせずに、ルールのメインページを短くするというのは、私の文章力では難しいので、誰か書いて…

2023-03-26 21:55 UTC, book000 commented on src/content/2.docs/1.rules/index.md
ん、これ「基本とするルール」の各項目について説明するページを作るつもりなやつですか？

2023-03-26 21:56 UTC, book000 commented on src/content/2.docs/1.rules/index.md
正直まあ別ページが作られてないのにindexでここまで討論というか指摘しても良くない気もしてきましたが…😇

2023-03-26 21:58 UTC, Hiratake commented on src/content/2.docs/1.rules/index.md
？
「**明示的に**制限されている行為」って話だったから、ルールに入れますという話だと思ってましたが。
（どこにも文書化されてないのなら明示的ではないと思うので）

2023-03-26 22:00 UTC, Hiratake commented on src/content/2.docs/1.rules/index.md
まあこの箇条書きの部分については、簡易版ルールというか全体の要約というかそういうものなので、別ページができてからまとめるほうが早いかもしれん

2023-03-26 22:01 UTC, Hiratake commented on src/content/2.docs/1.rules/index.md
そもそもの「ルールトップに簡易版として箇条書きする」という点に異論がなければ、後回しでいいかも。

2023-03-26 22:03 UTC, Hiratake commented on src/content/2.docs/1.rules/index.md
> +- MinecraftサーバやDiscordサーバからのキック・BANなどの処罰
追加のコミットで足してるのでよければresolveにしてください（私しかできないんだっけ？）

2023-03-26 22:09 UTC, Hiratake commented on src/content/2.docs/1.rules/index.md
> +既にコミュニティへご参加いただいている方は、お時間のあるときに読み返していただき、より良いコミュニティをつくっていくためにご意見などいただければと思います。
develop関係のチャンネル固まってるとこにあるfeedbacksって開発関係しか書いたらダメとかありましたっけ？
フィードバック用のチャンネルが複数あって用途によって違うとこに書いてねだと分かりづらそうなので、開発用とかルール用とかって分けるのはしたくないかも。
フォーラムにタグを作成できるぽいので、チャンネル分けるんじゃなくてタグつけてねってするのが分かりやすいのかねえ…

2023-03-26 22:54 UTC, book000 commented on src/content/2.docs/1.rules/index.md
まあ、ちょっとこの辺の話はルール関連のページができてきてからまた話をするかも。

2023-03-26 22:57 UTC, book000 commented on src/content/2.docs/1.rules/index.md
> +既にコミュニティへご参加いただいている方は、お時間のあるときに読み返していただき、より良いコミュニティをつくっていくためにご意見などいただければと思います。
ダメとも言ってないけど、まああんまり…とは思ってたりしますね（開発関連のチャンネルミュートしてる運営や常連がある程度いるので）
うーん、どうしよかしら

2023-03-26 23:09 UTC, Hiratake commented on src/content/2.docs/1.rules/index.md
> +既にコミュニティへご参加いただいている方は、お時間のあるときに読み返していただき、より良いコミュニティをつくっていくためにご意見などいただければと思います。
場所をどこにするかについては、一旦おいときますか…
ルール考えるということについての本質的なとこじゃない気がするので。

2023-03-26 23:13 UTC, Hiratake commented on src/content/2.docs/1.rules/index.md
まあそう。
全体できてきたら、コミュニティ全体に意見聞くとかしてもいいかも。どっちもより良いものにしようとしてるわけだけど、2人だけじゃ互いの意見のぶつかりあいにしかならないので。

2023-03-26 23:26 UTC, Hiratake commented on src/content/2.docs/1.rules/index.md
> +既にコミュニティへご参加いただいている方は、お時間のあるときに読み返していただき、より良いコミュニティをつくっていくためにご意見などいただければと思います。
とりあえず場所についての記述を仮で追加しました。

2023-03-26 23:30 UTC, book000 commented on src/content/2.docs/1.rules/index.md
> +既にコミュニティへご参加いただいている方は、お時間のあるときに読み返していただき、より良いコミュニティをつくっていくためにご意見などいただければと思います。
👍

2023-03-26 23:32 UTC, Hiratake commented on src/content/2.docs/1.rules/index.md
> +既にコミュニティへご参加いただいている方は、お時間のあるときに読み返していただき、より良いコミュニティをつくっていくためにご意見などいただければと思います。
🙏

2023-03-29 15:49 UTC, Hiratake commented
タイトルとファイル名がなんもわからんので誰かいい感じにしてください。
中身もなんもわかりません。

2023-03-29 18:20 UTC, book000 requested changes

2023-03-29 18:20 UTC, book000 commented on src/content/2.docs/1.rules/1.build.md
> +
```suggestion
- 政治的な思想や宗教的な思想を示唆する表現

```

公序良俗から外れるので微妙なのですが、これは書いといても良いと思います。
参考にしているルールでは「反社会的な」とつけていましたが、どうあれ政治的な発言とか建築物はやめてほしいと思うので、まあつけなくてもいいかなって感じです

2023-03-29 18:20 UTC, book000 commented on src/content/2.docs/1.rules/1.build.md
> +この**自由建築エリアの外で、許可なく建物やオブジェなどを制作してはいけません**。
```suggestion
Minecraftサーバ内には、どなたでも自由に建物や作品などを制作をすることができる自由建築エリア（「中央市」と呼ばれています）をご用意しております。  
この**自由建築エリアの外で、許可なく建物や作品などを制作してはいけません**。
```

2023-03-29 18:20 UTC, book000 commented on src/content/2.docs/1.rules/1.build.md
> +このエリアは、運営チームに申請し許可を得ることによって使うことができます。
```suggestion
このエリアは、運営チームに申請し承認されることで利用できます。
```

細かいですが、許可を得るというより自治体を認めるというイメージになるかなあと思います。

2023-03-29 18:20 UTC, book000 commented on src/content/2.docs/1.rules/1.build.md
> +  - ルール
```suggestion
  - ルール
  - Minecraft
```

Minecraftサーバに関するルールなので、MinecraftタグないしMinecraftサーバルール的なタグ付けをして一覧にできたらなあと思ったりします

2023-03-30 00:28 UTC, Hiratake commented on src/content/2.docs/1.rules/1.build.md
> +- Minecraftサーバでの制作、ブロックの設置・破壊
そこ悩んでてとりあえず入れといたんだけど、まあ、いらんか。

2023-03-30 00:40 UTC, Hiratake commented on src/content/2.docs/1.rules/1.build.md
> +
これ、入れるか悩んだんだけど、Discordでの色々（とくにVC、そういう曲が定期的に流れてる）があるので難しいなあと思ってます。
あと、普通にマイクラで教会みたいのを建てたいですってなったときに、それは宗教的なものだからダメですってことにするのかみたいなのは議論必要そうかなあと。

2023-03-30 00:46 UTC, Hiratake commented on src/content/2.docs/1.rules/1.build.md
> +  - ルール
ブログ記事一覧のとこみたいに、ルールのトップページにタグで絞り込む表示を入れたらいいかも？

2023-03-30 00:49 UTC, Hiratake commented on src/content/2.docs/1.rules/1.build.md
> +title: 制作についてのルール
建築か制作（製作？）で悩んでました。建築のほうがマイクラっぽい（？）し建築にします？
もっと良さげな他アイデア出てきたらまた置き換える感じで。

2023-03-30 00:54 UTC, Hiratake commented on src/content/2.docs/1.rules/1.build.md
> +Minecraftサーバ内には、他の参加者が制作した建物やオブジェなどが存在します。**どのような理由があっても、これらを許可なく変更・破壊してはいけません**。
個人的に制作者のほうがいいかもと思ってますがどうでしょう。まあどっちでも伝わるとは思うけど。

2023-03-30 00:58 UTC, Hiratake commented on src/content/2.docs/1.rules/1.build.md
> +title: 制作についてのルール
建築に変えたら、制作になってるところを建築に変えないとかもだねえ

2023-03-30 01:25 UTC, Hiratake commented on src/content/2.docs/1.rules/1.build.md
> +
政治とか宗教とかに基づいて他の参加者を攻撃するような表現、みたいな感じかねえ。入れるとしたら。

2023-03-30 04:51 UTC, book000 commented on src/content/2.docs/1.rules/1.build.md
> +Minecraftサーバ内には、他の参加者が制作した建物やオブジェなどが存在します。**どのような理由があっても、これらを許可なく変更・破壊してはいけません**。
製作者でも良いです。

2023-03-30 04:53 UTC, Hiratake commented on src/content/2.docs/1.rules/1.build.md
> +Minecraftサーバ内には、他の参加者が制作した建物やオブジェなどが存在します。**どのような理由があっても、これらを許可なく変更・破壊してはいけません**。
https://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q1050053285
**制**作者でいいですか？

2023-03-30 04:53 UTC, Hiratake commented on src/content/2.docs/1.rules/1.build.md
> +Minecraftサーバ内には、他の参加者が制作した建物やオブジェなどが存在します。**どのような理由があっても、これらを許可なく変更・破壊してはいけません**。
てか建築者か

2023-03-30 04:56 UTC, book000 commented on src/content/2.docs/1.rules/1.build.md
> +Minecraftサーバ内には、他の参加者が制作した建物やオブジェなどが存在します。**どのような理由があっても、これらを許可なく変更・破壊してはいけません**。
ああごめんなさいなんも考えずに変換かけてぽちっとしてたわ。

https://news.1242.com/article/145123 とかを見る感じ、創作活動にあたるので「制作」ですね。まあ建築で統一するのであれば「建築者」になるのでしょうか

2023-03-30 05:00 UTC, book000 commented on src/content/2.docs/1.rules/1.build.md
> +
攻撃、攻撃ねえ…。まあとりあえず

```suggestion
- 政治的な思想や宗教的な思想に基づいて他の参加者を攻撃、またはその恐れがある表現

```

かなあ。曖昧で嫌なら「その恐れがある」を弾いてもいいです。
万一そういう問題が出てきたときには他のユーザーからの指摘でやめるよう指示 + このあたりの再検討が必要でしょうかね。

2023-03-30 05:01 UTC, book000 commented on src/content/2.docs/1.rules/1.build.md
> +  - ルール
`:filter='true'` つけると使いやすそうですねえ

2023-03-30 05:38 UTC, Hiratake commented on src/content/2.docs/1.rules/1.build.md
> +  - ルール
書いた人のフィルターも出ちゃうんですよねえ。ルールではいらんよなあ。

2023-03-30 05:38 UTC, Hiratake commented on src/content/2.docs/1.rules/1.build.md
> +
そうだねえ、問題でてきたときに考えるかねえ

2023-03-30 05:39 UTC, book000 commented on src/content/2.docs/1.rules/1.build.md
> +  - ルール
ルールではいらないですねえ… `filter-user` `filter-tag` で別フラグにするしかないか？

2023-03-30 05:41 UTC, Hiratake commented on src/content/2.docs/1.rules/1.build.md
> +  - ルール
つくって♡

2023-03-30 05:44 UTC, book000 commented on src/content/2.docs/1.rules/1.build.md
> +  - ルール
:thinking:

2023-03-30 06:06 UTC, book000 commented on src/content/2.docs/1.rules/1.build.md
> +  - ルール
https://github.com/jaoafa/jaoweb4/pull/86

2023-03-30 10:41 UTC, Hiratake commented on src/content/2.docs/1.rules/1.build.md
> +  - ルール
🙏

2023-03-30 10:42 UTC, Hiratake commented on src/content/2.docs/1.rules/1.build.md
> +  - ルール
とりあえず仮で `ルール` タグ入れてたけど、いらない気がしますよね

2023-03-30 10:45 UTC, Hiratake commented on src/content/2.docs/1.rules/1.build.md
> +このエリアは、運営チームに申請し許可を得ることによって使うことができます。
この文だけ変えたら見出しの `自由建築エリアの外で許可なく制作をしない` と合わなくなると思うので、他の箇所も変える必要ありますね。

2023-03-30 11:01 UTC, Hiratake commented
制作についてのルールとしていたものを、建築についてのルールに変えました。（あと細かいところの調整など）
他にも、書いた方がいい項目とかたぶんあると思うので、思いついたら見出しとか増やしてコミットなどしてください🙏

2023-03-30 11:03 UTC, Hiratake commented on src/content/2.docs/1.rules/1.build.md
> +title: 制作についてのルール
かえました

2023-03-30 11:03 UTC, Hiratake commented on src/content/2.docs/1.rules/1.build.md
> +Minecraftサーバ内には、他の参加者が制作した建物やオブジェなどが存在します。**どのような理由があっても、これらを許可なく変更・破壊してはいけません**。
かえました

2023-03-30 11:03 UTC, Hiratake commented on src/content/2.docs/1.rules/1.build.md
> +このエリアは、運営チームに申請し許可を得ることによって使うことができます。
いったんかえてみました

2023-03-30 14:17 UTC, book000 requested changes

2023-03-30 14:18 UTC, Hiratake commented on src/content/2.docs/1.rules/1.build.md
> +## 他の参加者建築物を許可なく変更・破壊しない
あっ…普通に脱字です…

2023-03-30 14:19 UTC, book000 commented on src/content/2.docs/1.rules/1.build.md
> +## 他の参加者建築物を許可なく変更・破壊しない
😢

2023-03-31 06:14 UTC, book000 commented on src/content/2.docs/1.rules/1.build.md
> +このエリアは、運営チームに申請し承認を得ることによって使うことができます。
であれば以下ですかね

```suggestion
自由建築エリアの外は、以下のような場合に使うことができるエリアとなっています。

- 自分だけの街をつくりたい
- 自由建築エリアに収まらない巨大な建物をつくりたい

このエリアは、運営チームに申請し承認を得ることによって使うことができます。
```

「以下のような場合に使うことができるエリア」がどっちにしても冗長な気もしますが…。「使うことができる」を「利用できる」に置き換えるとか？

2023-03-31 06:24 UTC, Hiratake commented on src/content/2.docs/1.rules/1.build.md
> +このエリアは、運営チームに申請し承認を得ることによって使うことができます。
どっちも意味は一緒な気はしますが、なんとなく「利用できる」のほうがおかたい印象ありますね。
ルールだし「利用できる」のほうがいいのかねえ。

2023-04-01 08:24 UTC, Hiratake commented on src/content/2.docs/1.rules/1.build.md
> +このエリアは、運営チームに申請し承認を得ることによって使うことができます。
変えました

2023-04-14 12:03 UTC, book000 commented
ちょっといつまでもマージしないのもアレなので（fork先で作業したものをそのままにしているとこっちからPR出しにくい）、いったん `feat/rules` ブランチを作ってベースを切り替えました
この2ファイルでとりあえずひと段落しているように見えるので（チャットの話とかまだまだ追加する必要があるけど、それをすべてこのPRにまとめる必要はないかな）、よければいったんマージ頂けますか？
オムレツとかその他運営のレビューはmainへのPRでやりましょう

2023-04-16 03:02 UTC, book000 approved these changes

2023-04-16 03:03 UTC, merged